# Generated by Django 5.2.6 on 2025-11-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True, help_text="Загрузите свой аватар", null=True, upload_to="avatars/", verbose_name="Аватар"
            ),
        ),
    ]
