# Generated by Django 5.2.6 on 2025-10-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("content", models.TextField(null=True, verbose_name="Содержимое")),
                ("preview", models.ImageField(blank=True, null=True, upload_to="blog/", verbose_name="Превью")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата изменения")),
                ("is_published", models.BooleanField(default=False, verbose_name="Опубликовано")),
                ("views", models.PositiveIntegerField(default=0, verbose_name="Просмотры")),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
                "ordering": ["-created_at"],
            },
        ),
    ]
