# Generated by Django 5.2.6 on 2025-10-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="Skystore", max_length=100, verbose_name="Организация")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="Email")),
                ("phone", models.CharField(blank=True, max_length=50, verbose_name="Телефон")),
                ("address", models.CharField(blank=True, max_length=255, verbose_name="Адрес")),
                ("working_hours", models.CharField(blank=True, max_length=255, verbose_name="Время работы")),
                ("telegram", models.URLField(blank=True, verbose_name="Telegram")),
                ("vk", models.URLField(blank=True, verbose_name="VK")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "ordering": ["-updated_at"],
            },
        ),
    ]
