# Generated by Django 5.2.6 on 2025-10-13 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="telegram",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="vk",
        ),
    ]
