# Generated by Django 5.2.6 on 2025-11-21 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_remove_contact_telegram_remove_contact_vk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "price", "created_at"],
                "permissions": [("can_unpublish_product", "Can unpublish product")],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
